### ISSUE TITLE
shematic

### ISSUE THREAD

**Issue by hyperion11** [isaac879/Pan-Tilt-Mount#13]
hello! in what program made schematic for control board?
i wish to modify it. 
Can you add it to github?
For my camera i need two wires  - shutter control and focus control. Without "clicking" focus it not release shutter (Sony A7S)
Thanks!

**Comment by Glivmo** [comment]
You can find the schematic and pcb design on easyeda and use the web editor to edit it:
https://easyeda.com/isaac879/pan-tilt-camera-mount_copy
