### ISSUE TITLE
Loop a movement?

### ISSUE THREAD

**Issue by dr00pyd** [isaac879/Pan-Tilt-Mount#6]
Hi, When you put the cameras on a keyframe and it continues to follow that object, can you make it loop and go back and forth until you choose to stop? I would like to use your project for my live stream so can can get a paralaxefect. Anyway I really like the project and so you can order pcbn, so I have done it now.

thanks so much.

**Comment by isaac879** [comment]
You can set the number of times for it to repeat a movement but unfortunately there currently isn't a way to stop it half way through.
